//! Masking coverage: every encoding, every split, and the limits.
//!
//! In the reference implementation this project was measured against, the
//! masking and injection paths sat at 0.0% test coverage and 6 of 13 encodings
//! leaked. Every variant here therefore gets a positive test, and — just as
//! important — the shapes that *cannot* be caught get a test that asserts they
//! are not caught. A documented limit is worth more than a comment claiming
//! coverage that does not exist.

mod support;

use keyless::mask::encodings::{ALL, Encoding};
use keyless::mask::{Masker, MaskingWriter};
use keyless::secret::Secret;
use std::io::Write;
use std::process::{Command, Stdio};
use std::sync::Arc;

/// A decoy chosen to exercise every escaping rule at once: mixed case, digits,
/// a space, a quote, the HTML trio, a slash, a plus, and a non-ASCII character.
///
/// It is 31 bytes on purpose. 31 divides by neither 3 nor 5, so base64 and
/// base32 both need padding and the padded and unpadded variants are genuinely
/// different strings — at 30 bytes they collide and half the table silently
/// stops testing anything.
const VALUE: &str = "Decoy-Key_é9 \"q\" &<>/ +42?=#~!";

/// Every encoding of [`VALUE`], written out as a literal.
///
/// These are **not** produced by the code under test. They were generated by
/// Python's `base64`, `binascii`, `urllib.parse` and `json` modules and pasted
/// here, so this table is an independent oracle for the hand-rolled codecs.
///
/// That independence is the point, and it was learned the hard way: an earlier
/// version of these tests iterated `encodings::ALL` and asserted each variant
/// was masked. Deleting an encoding from `ALL` deleted it from the test in the
/// same stroke, and the suite stayed green — the exact shape of failure that
/// let 6 of 13 encodings leak in the reference implementation. A literal cannot
/// be deleted by editing the source it is supposed to check.
const EXPECTED: [(&str, &str); 20] = [
    ("raw", "Decoy-Key_é9 \"q\" &<>/ +42?=#~!"),
    ("lowercase", "decoy-key_é9 \"q\" &<>/ +42?=#~!"),
    ("uppercase", "DECOY-KEY_É9 \"Q\" &<>/ +42?=#~!"),
    ("base64-std", "RGVjb3ktS2V5X8OpOSAicSIgJjw+LyArNDI/PSN+IQ=="),
    (
        "base64-std-nopad",
        "RGVjb3ktS2V5X8OpOSAicSIgJjw+LyArNDI/PSN+IQ",
    ),
    ("base64-url", "RGVjb3ktS2V5X8OpOSAicSIgJjw-LyArNDI_PSN-IQ=="),
    (
        "base64-url-nopad",
        "RGVjb3ktS2V5X8OpOSAicSIgJjw-LyArNDI_PSN-IQ",
    ),
    (
        "base32",
        "IRSWG33ZFVFWK6K7YOUTSIBCOERCAJR4HYXSAKZUGI7T2I36EE======",
    ),
    (
        "base32-nopad",
        "IRSWG33ZFVFWK6K7YOUTSIBCOERCAJR4HYXSAKZUGI7T2I36EE",
    ),
    (
        "hex-lower",
        "4465636f792d4b65795fc3a9392022712220263c3e2f202b34323f3d237e21",
    ),
    (
        "hex-upper",
        "4465636F792D4B65795FC3A9392022712220263C3E2F202B34323F3D237E21",
    ),
    (
        "hex-0x-lower",
        "0x4465636f792d4b65795fc3a9392022712220263c3e2f202b34323f3d237e21",
    ),
    (
        "hex-0x-upper",
        "0x4465636F792D4B65795FC3A9392022712220263C3E2F202B34323F3D237E21",
    ),
    (
        "url-query",
        "Decoy-Key_%C3%A99+%22q%22+%26%3C%3E%2F+%2B42%3F%3D%23~%21",
    ),
    (
        "url-path",
        "Decoy-Key_%C3%A99%20%22q%22%20&%3C%3E%2F%20+42%3F=%23~%21",
    ),
    (
        "url-strict",
        "Decoy-Key_%C3%A99%20%22q%22%20%26%3C%3E%2F%20%2B42%3F%3D%23~%21",
    ),
    ("json-minimal", "Decoy-Key_é9 \\\"q\\\" &<>/ +42?=#~!"),
    (
        "json-html",
        "Decoy-Key_é9 \\\"q\\\" \\u0026\\u003c\\u003e/ +42?=#~!",
    ),
    ("json-slash", "Decoy-Key_é9 \\\"q\\\" &<>\\/ +42?=#~!"),
    (
        "json-ascii-only",
        "Decoy-Key_\\u00e99 \\\"q\\\" &<>/ +42?=#~!",
    ),
];

/// The encoding carrying `label`, or a failure naming what went missing.
fn encoding_named(label: &str) -> Encoding {
    *ALL.iter()
        .find(|encoding| encoding.label() == label)
        .unwrap_or_else(|| panic!("the `{label}` encoding is no longer generated"))
}

fn masker() -> Arc<Masker> {
    let secret = Secret::new(VALUE.to_owned());
    Arc::new(Masker::from_secrets([("DECOY", &secret)]))
}

fn through_stream(masker: &Arc<Masker>, text: &str, split_at: usize) -> String {
    let mut sink: Vec<u8> = Vec::new();
    {
        let mut writer = MaskingWriter::new(Arc::clone(masker), &mut sink);
        let bytes = text.as_bytes();
        let split = split_at.min(bytes.len());
        writer.write_all(&bytes[..split]).expect("write");
        writer.write_all(&bytes[split..]).expect("write");
        writer.finish().expect("finish");
    }
    String::from_utf8_lossy(&sink).into_owned()
}

#[test]
fn the_codecs_agree_with_an_independent_oracle() {
    // The hand-rolled base64, base32, hex, percent-encoding and JSON escaping
    // must produce byte-for-byte what Python's standard library produces.
    // Owning a codec is only cheaper than depending on one if it is checked.
    for (label, expected) in EXPECTED {
        let produced = encoding_named(label).encode(VALUE);
        assert_eq!(
            produced, expected,
            "the `{label}` codec disagrees with the oracle"
        );
    }
}

#[test]
fn every_encoding_in_the_table_is_caught_in_a_stream() {
    let masker = masker();
    for (label, rendered) in EXPECTED {
        let line = format!("log line: {rendered} <- end\n");

        // Whole write.
        let masked = through_stream(&masker, &line, line.len());
        assert!(
            !masked.contains(rendered),
            "{label} leaked on a whole write: {masked}"
        );
        assert!(
            masked.contains("[keyless:DECOY]"),
            "{label} produced no mask token: {masked}"
        );

        // Split in the middle of the encoded value — the case a line-oriented
        // matcher gets wrong.
        let middle = "log line: ".len() + rendered.len() / 2;
        let masked = through_stream(&masker, &line, middle);
        assert!(
            !masked.contains(rendered),
            "{label} leaked when split mid-value"
        );
    }
}

#[test]
fn every_encoding_in_the_table_is_caught_at_every_split_point() {
    let masker = masker();
    for (label, rendered) in EXPECTED {
        let line = format!("a{rendered}b");
        for split in 0..=line.len() {
            let masked = through_stream(&masker, &line, split);
            assert!(
                !masked.contains(rendered),
                "{label} leaked when split at byte {split}"
            );
            // An ABSENCE on its own is not a result. This test used to assert
            // only the line above, and a masker that emitted nothing at all
            // satisfied it: the empty string contains no secret. Measured by
            // making `Masker::scan` return an empty buffer — a masker that
            // deletes the whole stream — after which this test stayed green
            // across all twenty encodings and every split point.
            //
            // So the output is pinned exactly. The bracketing `a` and `b` are
            // what make it exact rather than a second `contains`: they prove
            // the bytes around the match survived and that the replacement
            // landed in their place, not merely somewhere.
            assert_eq!(
                masked, "a[keyless:DECOY]b",
                "{label} at split {split}: the stream is not what it should be"
            );
        }
    }
}

#[test]
fn the_generated_set_and_the_table_describe_the_same_encodings() {
    // Catches both directions of drift: an encoding added to the code with no
    // literal to check it, and a literal left behind after an encoding is gone.
    let generated: Vec<&str> = ALL.iter().map(|encoding| encoding.label()).collect();
    let tabled: Vec<&str> = EXPECTED.iter().map(|(label, _)| *label).collect();
    assert_eq!(generated, tabled);
}

#[test]
fn a_credential_embedded_in_a_url_is_caught() {
    // The URL-embedded shape, one of the four the README's *Why this exists*
    // names. It is the one that needs its own test, because the credential sits
    // between a `:` and an `@` rather than at a word boundary.
    let secret = Secret::new("s3cr3t-decoy-password-9999".to_owned());
    let masker = Arc::new(Masker::from_secrets([("DB_PASSWORD", &secret)]));
    let line = "postgres://app:s3cr3t-decoy-password-9999@db.internal:5432/prod";
    let masked = through_stream(&masker, line, 20);
    assert_eq!(
        masked,
        "postgres://app:[keyless:DB_PASSWORD]@db.internal:5432/prod"
    );
}

#[test]
fn a_bearer_token_in_a_curl_trace_is_caught() {
    let secret = Secret::new("ghp_decoyDECOYdecoy0123456789abcd".to_owned());
    let masker = Arc::new(Masker::from_secrets([("GITHUB_TOKEN", &secret)]));
    let line = "> Authorization: Bearer ghp_decoyDECOYdecoy0123456789abcd\r\n";
    let masked = through_stream(&masker, line, 30);
    assert!(masked.contains("[keyless:GITHUB_TOKEN]"));
    assert!(!masked.contains("ghp_decoy"));
}

// ---------------------------------------------------------------------------
// Limits. These tests assert that masking does NOT catch something, on purpose.
// ---------------------------------------------------------------------------

#[test]
fn known_limit_compression_cannot_be_caught() {
    // Substring matching sees bytes. gzip preserves no contiguous byte image of
    // the input, so a compressed stream carrying the secret is invisible. This
    // is an accepted limit of the approach, written as a test so nobody later
    // claims coverage the design does not have.
    let masker = masker();

    // A missing tool is a broken environment, not a pass. This used to be
    // `Err(_) => return`, which made the whole test evaporate into a green tick
    // wherever `gzip` was absent — the one shape that is indistinguishable, from
    // the outside, from a limit that was actually demonstrated. Both CI runners
    // for this project (`ubuntu-latest`, `macos-latest`) ship `/usr/bin/gzip`,
    // so its absence is a fact worth failing on rather than skipping past.
    let mut gzip = Command::new("/usr/bin/gzip")
        .arg("-c")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap_or_else(|error| {
            panic!(
                "/usr/bin/gzip cannot be spawned ({error}). This test demonstrates \
                 an accepted limit of substring masking and needs a real compressor \
                 to do it; skipping it silently would report a limit as proven when \
                 nothing ran."
            )
        });
    gzip.stdin
        .take()
        .expect("piped stdin")
        .write_all(VALUE.as_bytes())
        .expect("write to gzip");
    let compressed = gzip.wait_with_output().expect("gzip output").stdout;

    // The precondition, stated. Everything below is only interesting because the
    // compressed bytes carry no contiguous image of the value; if they ever did,
    // masking would catch it and the failure would read as a masking bug rather
    // than as a fixture that stopped compressing.
    assert!(
        !compressed
            .windows(VALUE.len())
            .any(|window| window == VALUE.as_bytes()),
        "gzip left the value contiguous in its output, so this fixture is not \
         demonstrating the limit it claims to"
    );

    let masked = masker.mask_bytes(&compressed);
    assert_eq!(
        masked, compressed,
        "gzip output changed, so this test is no longer demonstrating the limit"
    );
}

#[test]
fn known_limit_a_secret_encoded_together_with_other_data_is_not_caught() {
    // HTTP Basic auth base64-encodes `user:password` as one string. base64 is
    // 3-byte aligned, so the encoding of the password alone is usually not a
    // substring of it, and the header survives masking.
    //
    // This is the sharpest limit in the whole approach and it is not
    // theoretical: `curl -u user:pass -v` prints exactly this. Catching it
    // needs the username as well, which this tool does not have.
    let password = "decoy-basic-auth-password-1234";
    let secret = Secret::new(password.to_owned());
    let masker = Arc::new(Masker::from_secrets([("PASSWORD", &secret)]));

    // Both forms are written out, for the reason the table at the top of this
    // file is written out. `Encoding::Base64Std.encode` used to BUILD the
    // header this test then asserted about, so both sides of that equality
    // moved together: corrupt the codec and the header changes, the masked copy
    // changes with it, and `masked == header` still holds. Measured by swapping
    // two symbols of `B64_STD` — this test stayed green while
    // `the_codecs_agree_with_an_independent_oracle` went red, which is the
    // difference between an oracle and an echo.
    const HEADER: &str = "YXBpdXNlcjpkZWNveS1iYXNpYy1hdXRoLXBhc3N3b3JkLTEyMzQ=";
    const PASSWORD_B64: &str = "ZGVjb3ktYmFzaWMtYXV0aC1wYXNzd29yZC0xMjM0";

    // The alignment claim, checked rather than asserted in prose. `apiuser:` is
    // eight bytes and eight is not a multiple of three, so the password's own
    // encoding starts on a different boundary inside the joined string. If a
    // later edit picks a username whose length IS a multiple of three, this
    // fires and says so, instead of the test quietly stopping being about
    // misalignment.
    assert!(
        !HEADER.contains(PASSWORD_B64),
        "the fixture no longer demonstrates misalignment: the password's own \
         base64 is a substring of the header, so masking would catch it"
    );

    // The codec is pinned against the literal here, once, as its own claim.
    // Everything below is then stated in terms of the literal, so a defect in
    // the codec reds this line rather than travelling silently into the
    // assertions about masking.
    assert_eq!(
        Encoding::Base64Std.encode(&format!("apiuser:{password}")),
        HEADER,
        "the codec no longer produces the header this test is written against"
    );

    let masked = masker.mask_str(HEADER);
    assert_eq!(
        masked, HEADER,
        "if this now masks, the limit has been closed and the docs must change"
    );

    // The raw form in the same line IS caught, which is the useful half.
    let line = format!("-u apiuser:{password} -> {HEADER}");
    let masked = masker.mask_str(&line);
    assert!(masked.contains("[keyless:PASSWORD]"));
    assert!(
        masked.contains(HEADER),
        "the encoded half still passes through"
    );
}

#[test]
fn known_limit_an_exfiltrating_child_is_not_stopped() {
    // Masking filters a stream; it does not confine a process. A child that
    // writes the value to a file never touches the masked stream at all.
    // This is by design: the threat model is a capable agent taking a
    // shortcut, not an adversary. Stating it as a test keeps the claim honest.
    let dir = support::scratch("exfiltration");
    let escaped = dir.join("escaped");

    let status = Command::new("/bin/sh")
        .arg("-c")
        .arg("printf '%s' \"$SECRET\" > \"$1\"")
        .arg("sh")
        .arg(&escaped)
        .env("SECRET", VALUE)
        .status()
        .expect("spawn");

    assert!(status.success());
    assert_eq!(
        std::fs::read_to_string(&escaped).expect("read"),
        VALUE,
        "three tokens defeat output masking, and that is an accepted limit"
    );
}
