//! Generating a value nobody chose.
//!
//! `keyless new` exists so that a credential can be created without a human or
//! an agent session ever seeing it. That only holds if the value is
//! unpredictable, so this module is deliberately small, dependency-free and
//! written to be read.
//!
//! # Why `/dev/urandom` and not a crate
//!
//! A random-number crate in the trusted path of a secrets tool is a supply-chain
//! surface bought to save fifteen lines. `/dev/urandom` is the kernel's CSPRNG on
//! macOS and Linux, it is seeded before userspace exists, and it never blocks
//! after boot. Reading it is the same shape as the rest of this crate: a
//! well-understood OS interface, read directly.
//!
//! A short read is an error rather than a shorter password. Silently generating
//! fewer bytes than asked for is exactly the class of failure that produces a
//! credential everyone believes is 32 characters long.
//!
//! # Why the alphabet has exactly 64 characters
//!
//! `byte % 64` is `byte & 0x3F`, which maps all 256 byte values onto 64 symbols
//! with no remainder — so every symbol is equally likely and there is no modulo
//! bias to reject-sample away. An alphabet of, say, 62 characters would make
//! `%` favour the first two symbols slightly, and the naive fix ("just use
//! modulo") is a real weakness that looks like arithmetic.
//!
//! The symbols are `A-Z`, `a-z`, `0-9`, `-` and `_`: safe in a URL, in a shell
//! word, in a `.env` file and in a JSON string, so a generated value cannot fail
//! later because of how it was quoted.

use std::fs::File;
use std::io::{self, Read};

use zeroize::Zeroize;

use crate::secret::Secret;

/// The 64 symbols a generated value is drawn from. Exactly 64; see the module docs.
const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

/// The default length of a generated value, in characters.
///
/// 32 symbols from a 64-symbol alphabet is 192 bits. Well past anything an
/// attacker guesses, short enough to paste into a provider's form when a service
/// insists on a length limit.
pub const DEFAULT_LENGTH: usize = 32;

/// The shortest value this tool will generate.
///
/// Not a style rule. A `--length 4` credential is a credential that will be
/// brute-forced, and the person who typed it will not be the person who finds
/// out. Refusing is cheaper than explaining.
pub const MIN_LENGTH: usize = 16;

/// The longest, so a typo cannot ask for a gigabyte.
pub const MAX_LENGTH: usize = 4096;

/// A fresh random value of `length` characters.
///
/// # Errors
///
/// [`io::Error`] when `/dev/urandom` cannot be opened or read, and
/// [`io::ErrorKind::InvalidInput`] when `length` is outside
/// [`MIN_LENGTH`]..=[`MAX_LENGTH`].
pub fn generate(length: usize) -> io::Result<Secret> {
    if !(MIN_LENGTH..=MAX_LENGTH).contains(&length) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("a generated value must be {MIN_LENGTH}-{MAX_LENGTH} characters, not {length}"),
        ));
    }

    let mut bytes = vec![0u8; length];
    let filled = File::open("/dev/urandom").and_then(|mut source| source.read_exact(&mut bytes));
    if let Err(error) = filled {
        bytes.zeroize();
        return Err(error);
    }

    // Mapped in place, so the raw entropy is overwritten by the symbols rather
    // than left in a second buffer nobody scrubs.
    for byte in &mut bytes {
        *byte = ALPHABET[usize::from(*byte & 0x3F)];
    }

    // `from_bytes` zeroizes `bytes`; the alphabet is ASCII so it is always UTF-8.
    Secret::from_bytes(bytes).ok_or_else(|| io::Error::other("generated bytes were not UTF-8"))
}

#[cfg(test)]
mod tests {
    use super::{ALPHABET, DEFAULT_LENGTH, MAX_LENGTH, MIN_LENGTH, generate};

    #[test]
    fn the_alphabet_is_exactly_sixty_four_distinct_symbols() {
        // The whole no-bias argument is this number. 63 or 65 symbols and `& 0x3F`
        // silently stops being uniform.
        assert_eq!(ALPHABET.len(), 64);
        let mut sorted = ALPHABET.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 64, "the alphabet repeats a symbol");
    }

    #[test]
    fn a_generated_value_has_the_requested_length_and_only_alphabet_symbols() {
        let secret = generate(DEFAULT_LENGTH).expect("/dev/urandom must be readable");
        assert_eq!(secret.len(), DEFAULT_LENGTH);
        assert!(
            secret.expose().bytes().all(|b| ALPHABET.contains(&b)),
            "a symbol outside the alphabet appeared"
        );
    }

    #[test]
    fn two_generated_values_differ() {
        // A trivially weak generator — a constant, an uninitialised buffer, a
        // counter — fails here and passes every other test in this file.
        let first = generate(MIN_LENGTH).expect("readable");
        let second = generate(MIN_LENGTH).expect("readable");
        assert_ne!(first.expose(), second.expose());
    }

    #[test]
    fn every_symbol_of_the_alphabet_shows_up_across_a_long_draw() {
        // Catches a mapping that only ever reaches part of the alphabet — a `%
        // 32`, a signed cast, an off-by-one mask. With 4096 draws the chance of a
        // correct generator missing any one of 64 symbols is about 64 * (63/64)^4096,
        // which is far below one in a billion.
        let secret = generate(MAX_LENGTH).expect("readable");
        for symbol in ALPHABET {
            assert!(
                secret.expose().bytes().any(|b| b == *symbol),
                "`{}` never appeared in 4096 draws",
                char::from(*symbol)
            );
        }
    }

    #[test]
    fn an_unsafe_length_is_refused_rather_than_clamped() {
        // Clamping would hand back a credential of a length nobody asked for and
        // say nothing, which is how a 4-character password ships.
        assert!(generate(MIN_LENGTH - 1).is_err());
        assert!(generate(0).is_err());
        assert!(generate(MAX_LENGTH + 1).is_err());
        assert!(generate(MIN_LENGTH).is_ok());
        assert!(generate(MAX_LENGTH).is_ok());
    }
}
